-- Tabela de advogados (para login) - VERSÃO CORRIGIDA
CREATE TABLE IF NOT EXISTS advogados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefone VARCHAR(20),
    especialidade VARCHAR(100),
    oab VARCHAR(20), -- COLUNA ADICIONADA
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);